<?xml version="1.0"?>
<package format="3">
  <name>jackal_basic_motion</name>
  <version>0.1.0</version>
  <description>Basic motion node for Jackal direction and speed commands.</description>
  <maintainer email="user@example.com">Jackal Development Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>jackal_motion_interfaces</depend>
  <depend>rclpy</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
